<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-1D8K0B0C" failures="1" tests="5" name="Test" time="97.75" errors="0" timestamp="2024-11-21T22:59:22 IST">
  <testcase classname="tests.Json_Test" name="EndTEndTest" time="16.143"/>
  <testcase classname="tests.Json_Test" name="EndTEndTest" time="2.51">
    <skipped/>
  </testcase> <!-- EndTEndTest -->
  <testcase classname="tests.Json_Test" name="EndTEndTest" time="16.354"/>
  <testcase classname="tests.StandAlonePageObject" name="EndTEndTest" time="17.203">
    <skipped/>
  </testcase> <!-- EndTEndTest -->
  <testcase classname="tests.StandAlonePageObject" name="EndTEndTest" time="18.047">
    <failure type="java.lang.AssertionError" message="expected [THANKYOU FOR THE ORDER.] but found [THANKYO FOR THE ORDER.]">
      <![CDATA[java.lang.AssertionError: expected [THANKYOU FOR THE ORDER.] but found [THANKYO FOR THE ORDER.]
at tests.StandAlonePageObject.EndTEndTest(StandAlonePageObject.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- EndTEndTest -->
</testsuite> <!-- Test -->
